Repository DIT113-V22/group-17, pull requests merged in 2022-05, with the labels that each got.

#27 Implemented Speedometer
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/res/drawable/speedometer_colour.png
  SmartCarApp/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #2

#28 Speedometer minor updates
  arduino/smartcar/smartcar.ino
Labels: Sprint #2

#30 Dark mode and Settings
  SmartCarApp/app/src/main/AndroidManifest.xml
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/Settings.java
  SmartCarApp/app/src/main/res/anim/slide_in_left.xml
  SmartCarApp/app/src/main/res/anim/slide_in_right.xml
  SmartCarApp/app/src/main/res/anim/slide_out_left.xml
  SmartCarApp/app/src/main/res/anim/slide_out_right.xml
  SmartCarApp/app/src/main/res/drawable/icons8_house_50.png
  SmartCarApp/app/src/main/res/drawable/icons8_settings_50.png
  SmartCarApp/app/src/main/res/drawable/icons8_shutdown_48.png
  SmartCarApp/app/src/main/res/drawable/icons8_video_games_64.png
  SmartCarApp/app/src/main/res/layout/activity_main.xml
  SmartCarApp/app/src/main/res/layout/settings.xml
  SmartCarApp/app/src/main/res/values-night/themes.xml
  SmartCarApp/app/src/main/res/values/attr.xml
  SmartCarApp/app/src/main/res/values/colors.xml
  SmartCarApp/app/src/main/res/values/themes.xml
Labels: Sprint #2

#31 Speedometer Adjustments
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/res/layout/activity_main.xml
Labels: Sprint #2

#32 Voice commands
  SmartCarApp/app/src/main/AndroidManifest.xml
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MultiThread.java
  SmartCarApp/app/src/main/res/drawable/google_voice.png
  SmartCarApp/app/src/main/res/drawable/microphone.png
  SmartCarApp/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #2

#36 Implemented Travelled Distance
  SmartCarApp/app/src/main/AndroidManifest.xml
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MultiThread.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/UsefulFunctions.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/UserData.java
  SmartCarApp/app/src/main/res/layout/activity_main.xml
  SmartCarApp/build.gradle
  arduino/smartcar/smartcar.ino
Labels: Sprint #3

#38 Improved bottom navigation bar and major refactoring
  SmartCarApp/app/build.gradle
  SmartCarApp/app/src/main/AndroidManifest.xml
  SmartCarApp/app/src/main/java/com/example/smartcarapp/HomeFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MqttClient.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/ProfileFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/Settings.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/SettingsFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/SpeechToText.java
  SmartCarApp/app/src/main/res/drawable/ic_baseline_gamepad_24.xml
  SmartCarApp/app/src/main/res/drawable/ic_baseline_person_24.xml
  SmartCarApp/app/src/main/res/drawable/ic_baseline_settings_24.xml
  SmartCarApp/app/src/main/res/drawable/ic_baseline_sports_esports_24.xml
  SmartCarApp/app/src/main/res/drawable/icons8_house_50.png
  SmartCarApp/app/src/main/res/drawable/icons8_shutdown_48.png
  SmartCarApp/app/src/main/res/layout/activity_main.xml
  SmartCarApp/app/src/main/res/layout/fragment_home.xml
  SmartCarApp/app/src/main/res/layout/fragment_profile.xml
  SmartCarApp/app/src/main/res/layout/fragment_settings.xml
  SmartCarApp/app/src/main/res/layout/settings.xml
  SmartCarApp/app/src/main/res/menu/bottom_nav_menu.xml
  SmartCarApp/app/src/main/res/values/attr.xml
  SmartCarApp/app/src/main/res/values/strings.xml
  SmartCarApp/build.gradle
  SmartCarApp/gradle/wrapper/gradle-wrapper.properties
Labels: Sprint #2, Sprint #3

#41 Dark Mode
  SmartCarApp/app/build.gradle
  SmartCarApp/app/src/main/AndroidManifest.xml
  SmartCarApp/app/src/main/java/com/example/smartcarapp/HomeFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/LogInScreen.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MainActivity.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/MqttClient.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/SettingsFragment.java
  SmartCarApp/app/src/main/res/drawable-v24/shinagawa.jpg
  SmartCarApp/app/src/main/res/drawable/ic_baseline_gamepad_24.xml
  SmartCarApp/app/src/main/res/drawable/icons8_chevron_left_75.png
  SmartCarApp/app/src/main/res/drawable/icons8_settings_50.png
  SmartCarApp/app/src/main/res/drawable/icons8_video_games_64.png
  SmartCarApp/app/src/main/res/drawable/microphone.png
  SmartCarApp/app/src/main/res/drawable/roundedcorners.xml
  SmartCarApp/app/src/main/res/layout/fragment_home.xml
  SmartCarApp/app/src/main/res/layout/fragment_profile.xml
  SmartCarApp/app/src/main/res/layout/fragment_settings.xml
  SmartCarApp/app/src/main/res/layout/login.xml
  SmartCarApp/app/src/main/res/values-night/themes.xml
  SmartCarApp/app/src/main/res/values/colors.xml
  SmartCarApp/app/src/main/res/values/themes.xml
  SmartCarApp/gradle/wrapper/gradle-wrapper.properties
Labels: bug

#43 Limit speed
  SmartCarApp/app/src/main/java/com/example/smartcarapp/HomeFragment.java
  SmartCarApp/app/src/main/res/drawable-v24/icons8_plus_48.png
  SmartCarApp/app/src/main/res/drawable/ic_baseline_minimize_48.xml
  SmartCarApp/app/src/main/res/layout/fragment_home.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #3

#46 Fixed the camera colors
  SmartCarApp/app/src/main/java/com/example/smartcarapp/HomeFragment.java
Labels: bug

#48 Travelled Distance
  arduino/smartcar/smartcar.ino
Labels: bug

#39 Emulator modification
  Emulator_mods/Emulator_mods.zip
  Emulator_mods/Objects/Material_001.material
  Emulator_mods/Objects/MyTree.glb
  Emulator_mods/Objects/MyTree.glb.import
  Emulator_mods/Objects/MyTree.tscn
  Emulator_mods/Objects/Trashcan.glb
  Emulator_mods/Objects/Trashcan.glb.import
  Emulator_mods/Street Lamp.obj.import
  Emulator_mods/Street_Lamp.mtl
  Emulator_mods/car.mtl
  Emulator_mods/car.obj.import
  Emulator_mods/default_env.tres
  Emulator_mods/export_presets.cfg
  Emulator_mods/mods/City.gd
  Emulator_mods/project.godot
  Emulator_mods/src/environments/City/City.tscn
  Emulator_mods/stone.mtl
  Emulator_mods/stone.obj.import
  Emulator_mods/textures/leaves_pixelated.png
  Emulator_mods/textures/leaves_pixelated.png.import
  Emulator_mods/textures/pavement.jpg
  Emulator_mods/textures/pavement.jpg.import
  Emulator_mods/textures/wall.jpg
  Emulator_mods/textures/wall.jpg.import
Labels: Sprint #2, Sprint #3

#50 Travelled Distance Fix
  SmartCarApp/app/src/main/java/com/example/smartcarapp/HomeFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/SpeechToText.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/UsefulFunctions.java
  arduino/smartcar/smartcar.ino
Labels: bug

#52 Improved Manual Control
  SmartCarApp/app/src/main/AndroidManifest.xml
  SmartCarApp/app/src/main/java/com/example/smartcarapp/HomeFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/LogInScreen.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/SettingsFragment.java
  SmartCarApp/app/src/main/java/com/example/smartcarapp/UserData.java
  SmartCarApp/app/src/main/res/drawable-v24/shinagawa.jpg
  SmartCarApp/app/src/main/res/drawable/roundedcorners.xml
  SmartCarApp/app/src/main/res/layout/fragment_settings.xml
  SmartCarApp/app/src/main/res/layout/login.xml
  SmartCarApp/app/src/main/res/values/themes.xml
Labels: enhancement, Sprint #4

#54 UI changes, and removal of unneeded code
  SmartCarApp/app/src/main/res/anim/slide_in_left.xml
  SmartCarApp/app/src/main/res/anim/slide_in_right.xml
  SmartCarApp/app/src/main/res/anim/slide_out_left.xml
  SmartCarApp/app/src/main/res/anim/slide_out_right.xml
  SmartCarApp/app/src/main/res/layout/fragment_home.xml
  SmartCarApp/app/src/main/res/layout/fragment_profile.xml
  SmartCarApp/app/src/main/res/values/themes.xml
Labels: bug, enhancement
